### ISSUE TITLE
try this

### ISSUE THREAD

**Issue by aymende7** [PP29/pavan2329#1]
this will fix signal 6 error & resize the bootanimation to 480x800
1.Copy [bootanimation.zip](https://github.com/aymende7/Miui8_S2Plus/raw/master/other/bootanimation.zip) to /device/other/ don't unzip it
2.add this lines to customize_target_files.sh
`#updating bootanimation.zip`
`rm -rf "out/target_files/SYSTEM/media/bootanimation.zip"`
`cp -rf other/bootanimation.zip out/target_files/SYSTEM/media/`
3.delete (better backup this files to another folder) ResolverProxy$ProxyListAdapter.smali & ResolverProxy$ProxyListAdapter.smali from `framework.jar.out/smali/com/android/internal/app` thnx to warrenlobo
4.make fullota & send the logcat

**Comment by PP29** [comment]
bro when i add these..in make file...
@echo remove unnecessary libs!
    $(hide) rm -rf $(ZIP_DIR)/system/lib64
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libDecRes_sdk.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libjni_eglfence.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libjni_filtershow_filters.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libjni_jpegstream.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libjni_latinime.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libjni_terminal.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/librsjni.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libminivenus.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libmresearch.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libsecurities_sdk.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libwebp.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libweibosdkcore_sogou.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/libxmpass_sdk_patcher.so
    $(hide) rm -rf $(ZIP_DIR)/system/lib/xmpass_libweibosdkcore.so
    @echo remove unnecessary files!
    $(hide) rm -rf $(ZIP_DIR)/system/etc/CHANGELOG-CM.txt
    $(hide) rm -rf $(ZIP_DIR)/system/recovery-from-boot.bak
    $(hide) rm -rf $(ZIP_DIR)/system/media/audio/*
    @echo use only miui sounds!
    $(hide) cp -rf $(PORT_ROOT)/miui/system/media/$(local-density)/audio/*
$(ZIP_DIR)/system/media/audio
        $(hide) rm -rf
$(ZIP_DIR)/system/media/audio/create_symlink_for_audio-timestamp

i got this output....any solution about this..

pavan2329@ubuntu:~/bin/patchrom/device$ make fullota
makefile:83: *** missing separator (did you mean TAB instead of 8
spaces?).  Stop.

**Comment by aymende7** [comment]
Send your makefile

**Comment by PP29** [comment]
mate I cant focus on my problem right now.Bcz my exams are on 8th June. I
will mail you after my exams okey bro. and sorry for the late i was busy.
